### ISSUE TITLE
Sumokoin Support

### ISSUE THREAD

**Issue by CoFix** [Venthos/nodejs-pool#15]
Hi Venthos,

I am getting this error, when i try run sumocoin.

2018-04-14 12:57 +00:00: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: Cannot read property 'funcFile' of undefined
    at /home/sumo/nodejs-pool/init.js:46:42
    at tryCatcher (/home/sumo/nodejs-pool/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/sumo/nodejs-pool/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/sumo/nodejs-pool/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/sumo/nodejs-pool/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/sumo/nodejs-pool/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/sumo/nodejs-pool/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/sumo/nodejs-pool/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/sumo/nodejs-pool/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

What is the problem? How can i fix it?

**Comment by Venthos** [comment]
This nodejs-pool does not yet support sumokoin.  The error you have posted complains that the coin function file at /lib/coins/ does not exist for sumokoin, and it is correct.  It does not exist.

Unless you custom code it in, sumokoin is not usable with this repo at this time.

Self Note: A side requirement of this is updating node-cryptonight-hashing to support Cryptonight Heavy algorithm
